language: java
install: true

jdk:
  - openjdk16

addons:
  sonarcloud:
    organization: "arnosthavelka-github"
      
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dsonar.projectKey=arnosthavelka_spring-advanced-training

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
