# for all configuration options look here:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8080

spring:
  jackson:
    serialization:
      indent-output: true
  jmx:
    enabled: true
    default-domain: com.github.aha.sat.rest
  jpa:
    show-sql: true
    properties:
      hibernate:
      generate_statistics: true
sat-rest:
  cfg:
    author: Arny
        
endpoints:
  jolokia:
    enabled: true