spring:
    datasource:
        platform: HSQL
        url: jdbc:hsqldb:mem:mydb
        username: sa
        password:
        driverClassName: org.hsqldb.jdbcDriver
    sql:
        init:
            username: sa
            password: 
